"use client";

import { CalendarDays, CheckCircle2, Clock3, Info, MapPin, Plus, UsersRound, X } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import { PageHeader } from "@/components/app/page-header";
import { Button } from "@/components/ui/button";
import { Field, SelectField } from "@/components/ui/field";
import { useDemoStore } from "@/lib/demo-store";

type View = "day" | "week" | "month";
function initials(name: string) { return name.split(" ").slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }

export function ClassesScreen() {
  const params = useSearchParams();
  const { data, session, getClassAvailability, reserveClass, cancelClassBooking, createClassSession } = useDemoStore();
  const [view, setView] = useState<View>("week");
  const [modalOpen, setModalOpen] = useState(params.get("nova") === "1");
  const [title, setTitle] = useState("");
  const [date, setDate] = useState(() => new Date(Date.now() + 3 * 86_400_000).toISOString().slice(0, 10));
  const [startTime, setStartTime] = useState("18:00");
  const [duration, setDuration] = useState("45");
  const [capacity, setCapacity] = useState("12");
  const [professionalId, setProfessionalId] = useState("");
  const [waitlist, setWaitlist] = useState(true);
  const [formError, setFormError] = useState<string>();
  if (!session) return null;
  const canManage = session.role === "professional" || session.role === "organization_admin";
  const isStudent = session.role === "student";
  const professionals = data.memberships.filter((item) => item.role === "professional").map((membership) => data.users.find((user) => user.id === membership.userId)).filter((item): item is NonNullable<typeof item> => Boolean(item));
  const classes = [...data.classSessions].filter((item) => item.status === "scheduled").sort((a, b) => Date.parse(a.startsAt) - Date.parse(b.startsAt));

  function bookingFor(classId: string) { return data.classBookings.find((item) => item.classSessionId === classId && item.studentId === session?.userId && (item.status === "confirmed" || item.status === "waitlisted")); }
  function reserve(classId: string) { reserveClass({ classSessionId: classId }); }
  function cancel(bookingId: string) { if (window.confirm("Cancelar esta reserva? A vaga poderá ser liberada para outra pessoa.")) cancelClassBooking({ bookingId }); }
  function create() { const startsAt = new Date(`${date}T${startTime}:00-03:00`); const endsAt = new Date(startsAt.getTime() + Number(duration) * 60_000); if (title.trim().length < 3 || !Number.isFinite(startsAt.getTime()) || Number(capacity) < 1) { setFormError("Preencha nome, data, horário e capacidade válidos."); return; } const result = createClassSession({ title: title.trim(), professionalId: session?.role === "organization_admin" ? professionalId || professionals[0]?.id : undefined, startsAt: startsAt.toISOString(), endsAt: endsAt.toISOString(), capacity: Number(capacity), waitlistEnabled: waitlist }); if (result.ok) { setModalOpen(false); setTitle(""); setFormError(undefined); } else setFormError(result.error); }

  return <>
    <PageHeader eyebrow={isStudent ? "Agenda" : "Aulas e reservas"} title={isStudent ? "Escolha sua próxima aula" : "Agenda da academia"} description={isStudent ? "Reserve sua vaga, acompanhe a lotação e cancele com clareza quando precisar." : "Publique horários e acompanhe ocupação e lista de espera sem ultrapassar a capacidade."} actions={canManage ? <Button onClick={() => setModalOpen(true)}><Plus size={17} /><span>Nova aula</span></Button> : undefined} />
    <div className="agenda-toolbar"><div className="segmented" aria-label="Visualização da agenda">{(["day", "week", "month"] as View[]).map((item) => <button type="button" key={item} aria-pressed={view === item} onClick={() => setView(item)}>{item === "day" ? "Dia" : item === "week" ? "Semana" : "Mês"}</button>)}</div><div className="agenda-date"><CalendarDays size={17} /> {view === "day" ? "Hoje e próximas" : view === "week" ? "Semana de 17 a 23 jul" : "Julho de 2026"}</div></div>
    {classes.length === 0 ? <div className="empty-state"><div><span className="empty-state__icon"><CalendarDays size={23} /></span><h3>Nenhuma aula programada</h3><p>{canManage ? "Crie um horário para publicar na agenda." : "Novos horários aparecerão aqui."}</p></div></div> : <div className="class-grid">{classes.map((classSession) => { const teacher = data.users.find((user) => user.id === classSession.professionalId); const availability = getClassAvailability(classSession.id); const booking = isStudent ? bookingFor(classSession.id) : undefined; const occupied = availability?.confirmed ?? 0; const percent = Math.min(100, Math.round((occupied / classSession.capacity) * 100)); const full = (availability?.availableSpots ?? 0) === 0; const classBookings = data.classBookings.filter((item) => item.classSessionId === classSession.id && item.status === "confirmed"); return <article className="class-card" key={classSession.id}><div className="class-card__accent" /><div className="class-card__body"><span className="class-card__date"><CalendarDays size={14} /> {new Intl.DateTimeFormat("pt-BR", { weekday: "long", day: "2-digit", month: "short" }).format(new Date(classSession.startsAt))}</span><h3>{classSession.title}</h3><span className="class-card__teacher">com {teacher?.name ?? "Professor"}</span><div className="class-card__details"><span><Clock3 size={15} /> {new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit", timeZone: "America/Sao_Paulo" }).format(new Date(classSession.startsAt))} · {Math.round((Date.parse(classSession.endsAt) - Date.parse(classSession.startsAt)) / 60_000)} min</span><span><MapPin size={15} /> Unidade Centro · Sala Movimento</span></div><div className="booking-status"><div className="class-attendees">{classBookings.slice(0, 4).map((item) => { const user = data.users.find((candidate) => candidate.id === item.studentId); return user ? <span className="avatar" key={item.id}>{initials(user.name)}</span> : null; })}</div><span>{occupied}/{classSession.capacity} vagas · {availability?.waitlisted ?? 0} espera</span></div><div className="class-capacity"><div className="class-capacity__top"><span>{full ? "Turma lotada" : `${availability?.availableSpots ?? 0} vagas livres`}</span><strong>{percent}%</strong></div><div className="progress-track"><span style={{ width: `${percent}%` }} /></div></div>{isStudent ? booking ? <Button variant="secondary" onClick={() => cancel(booking.id)}>{booking.status === "confirmed" ? "Cancelar reserva" : "Sair da lista de espera"}</Button> : <Button onClick={() => reserve(classSession.id)}>{full && classSession.waitlistEnabled ? "Entrar na lista de espera" : full ? "Turma lotada" : "Reservar vaga"}</Button> : <div className="booking-status"><span className={`badge ${full ? "badge--warning" : "badge--success"}`}>{full ? "Lotada" : "Aberta"}</span><span>{availability?.waitlisted ? `${availability.waitlisted} aguardando` : "Sem lista de espera"}</span></div>}</div></article>; })}</div>}
    {modalOpen && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="class-title"><header className="modal__header"><div><h2 id="class-title">Criar aula</h2><p>O limite de vagas será aplicado de forma atômica no backend.</p></div><button className="modal__close" type="button" onClick={() => setModalOpen(false)} aria-label="Fechar"><X size={18} /></button></header><div className="modal__body"><div className="measurement-form">{formError && <div className="auth-error" role="alert"><Info size={17} /> {formError}</div>}<Field label="Nome da aula" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: Funcional express" />{session.role === "organization_admin" && <SelectField label="Professor" value={professionalId} onChange={(event) => setProfessionalId(event.target.value)}><option value="">Selecione</option>{professionals.map((person) => <option value={person.id} key={person.id}>{person.name}</option>)}</SelectField>}<div className="measurement-form__grid"><Field label="Data" type="date" value={date} onChange={(event) => setDate(event.target.value)} /><Field label="Início" type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} /><SelectField label="Duração" value={duration} onChange={(event) => setDuration(event.target.value)}><option value="30">30 minutos</option><option value="45">45 minutos</option><option value="60">60 minutos</option><option value="90">90 minutos</option></SelectField><Field label="Capacidade" type="number" min="1" max="200" value={capacity} onChange={(event) => setCapacity(event.target.value)} /></div><label className="toggle-row"><span><strong>Lista de espera automática</strong><small>Quando lotar, novas reservas entram em ordem.</small></span><input className="sr-only" type="checkbox" checked={waitlist} onChange={(event) => setWaitlist(event.target.checked)} /><button className="switch" type="button" role="switch" aria-checked={waitlist} onClick={() => setWaitlist((value) => !value)} /></label></div></div><footer className="modal__footer"><Button variant="secondary" onClick={() => setModalOpen(false)}>Cancelar</Button><Button onClick={create}><CheckCircle2 size={16} /> Publicar aula</Button></footer></section></div>}
  </>;
}
